vagrant_dir = __dir__
show_logo = false
branch_c = "\033[38;5;6m" # 111m"
red = "\033[38;5;9m" # 124m"
green = "\033[1;38;5;2m" # 22m"
blue = "\033[38;5;4m" # 33m"
purple = "\033[38;5;5m" # 129m"
docs = "\033[0m"
yellow = "\033[38;5;3m" # 136m"
yellow_underlined = "\033[4;38;5;3m" # 136m"
url = yellow_underlined
creset = "\033[0m"

Vagrant.configure("2") do |config|
 
  config.vm.box = "ubuntu/focal64"
  config.vm.network :private_network, ip: "192.168.3.10"
  config.vm.network "forwarded_port", guest: 3009, host: 3009
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus   = 2
  end  

  # Auto Download Vagrant plugins, supported from Vagrant 2.2.0
  unless Vagrant.has_plugin?('vagrant-goodhosts')
    if File.file?(File.join(vagrant_dir, 'vagrant-goodhosts.gem'))
      system('vagrant plugin install ' + File.join(vagrant_dir, 'vagrant-goodhosts.gem'))
      File.delete(File.join(vagrant_dir, 'vagrant-goodhosts.gem'))
      puts ("#{green} The vagrant-goodhosts plugin is now installed. Please run the requested command again.#{creset}")
      exit
    else
      config.vagrant.plugins = ['vagrant-goodhosts']
    end
  end

  puts ("#{yellow}Running start provision...#{creset}")
  

    # Auto Download Vagrant plugins, supported from Vagrant 2.2.0
  if Vagrant.has_plugin?('vagrant-goodhosts')
      puts ("#{yellow}Running vagrant goodhosts...#{creset}")
      config.vagrant.plugins = ['vagrant-goodhosts']
      config.goodhosts.aliases = ["dradis-ce.local", "dradis-dev.local"]
      config.goodhosts.remove_on_suspend = true
      config.goodhosts.disable_clean = true 
  else
      puts ("#{yellow}Running mv host name#{creset}")
      config.vm.hostname = "dradis-ce.local"
  end    

  puts ("#{yellow} Disabling default sync folder and adding new ones...#{creset}")
  config.vm.synced_folder '.', '/vagrant', disabled: true  # Disable the default synced folder to avoid overlapping mounts
  config.vm.synced_folder "#{vagrant_dir}/dradis/reports", '/home/dradis/reports', create: true, owner: 9001, group: 9001, mount_options: ['dmode=775', 'fmode=664']
 
  puts ("#{yellow}Running post provision...#{creset}")
  config.vm.provision "shell", path: "provision/provision-start.sh"  # In provision-start.sh, you can install the necessary components for your security testing environment.
  config.vm.provision "shell", path: "provision/provision-post.sh"  # In provision-post.sh, you can install the necessary components for your security testing environment.

end